language: cpp
compiler: 
  - clang
notifications:
  email: false
env:
  matrix: 
    # - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); Pkg.add("FactCheck"); Pkg.add("MarketData")'
  - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("TimeModels"))`); Pkg.pin("TimeModels"); Pkg.resolve()'
  - julia -e 'using TimeModels; @assert isdefined(:TimeModels); @assert typeof(TimeModels) === Module'
  - julia ./test/runtests.jl
